import { describe, expect, it } from 'vitest';
import type { AreaLookup } from './area-types';
import type { RideSession, SessionPoint } from './session-store';
import { isGeneratedSessionTitle, regionNamesForSession, titleForRegions } from './session-naming';

const point = (lng: number): SessionPoint => ({ lng, lat: 59.3, accuracy: 5, timestamp: lng });
const area = (name: string, adminLevel: number): AreaLookup['areas'][number] => ({
  area: { id: name, name, adminLevel, countryCode: 'SE', label: name, boundaryVersion: 'v1', geometry: null },
  job: null,
  automatic: false,
});

describe('session naming', () => {
  it('uses the same most specific area level as the map and keeps route order', async () => {
    const names = await regionNamesForSession([point(1), point(2), point(3)], async lng => ({
      source: 'catalog',
      areas: [area('Stockholms kommun', 7), area(lng === 3 ? 'Södermalms stadsdelsområde' : 'Enskede-Årsta-Vantörs stadsdelsområde', 9)],
    }));
    expect(names).toEqual(['Enskede-Årsta-Vantörs stadsdelsområde', 'Södermalms stadsdelsområde']);
    expect(titleForRegions(names)).toBe('Enskede-Årsta-Vantörs · Södermalm');
  });

  it('migrates autogenerated titles but preserves user names', () => {
    const session = { title: 'Årsta · Södermalm', districtNames: ['Årsta', 'Södermalm'] } as RideSession;
    expect(isGeneratedSessionTitle(session)).toBe(true);
    expect(isGeneratedSessionTitle({ ...session, title: 'ÅRSTA · SÖDERMALM' })).toBe(true);
    expect(isGeneratedSessionTitle({ ...session, districtNames: [] })).toBe(true);
    expect(isGeneratedSessionTitle({ ...session, title: 'Södermalm', districtNames: ['Södermalms stadsdelsområde'] })).toBe(true);
    expect(isGeneratedSessionTitle({ ...session, title: 'Evening commute' })).toBe(false);
  });
});
